#!/usr/bin/env python3
"""generate-pattern-routes — emit pattern-routes.tsv from the pattern registry's frontmatter.

Reads every `<registry>/*.md` (default registry: `.agent/patterns/`), parses the YAML-ish
frontmatter (`status`, `paths`, optional `route`), and writes one TSV row per (glob, pattern) pair:

    <glob> \t <pattern file relpath> \t <status> \t <route>

`paths:` in each pattern file is FACTUAL — the files that pattern governs (derived from its scope).
Routing POLICY is the `route:` field on each pattern (default `edit`), so it can change per pattern
without editing this script:

  - route=edit  → the pattern-guards hook reminds on the first Write/Edit of a governed path/session.
  - route=land  → too broad for edit-time (codebase-wide always-on rules would fire on nearly every
                  edit); reviewed at land-time (the pattern-compliance agent) instead. Mark a pattern
                  `route: land` in its frontmatter when its globs are effectively project-wide.

The registry dir is `.agent/patterns/` by default; override with PATTERN_REGISTRY_DIR (repo-relative).
The TSV is written INTO that dir (`<registry>/pattern-routes.tsv`) so it commits alongside the
registry. Run after adding/changing `paths:`/`route:` frontmatter or blessing a pattern:

    python3 <plugin>/hooks/generate-pattern-routes.py

Commit the regenerated TSV together with the pattern change. (The pattern-guards hook auto-runs this
on any write to a registry `*.md`, so it rarely needs running by hand.)
"""

from __future__ import annotations

import os
import re
import sys

TSV_NAME = "pattern-routes.tsv"


def registry_dir_rel() -> str:
    return os.environ.get("PATTERN_REGISTRY_DIR", os.path.join(".agent", "patterns"))


def parse_frontmatter(text: str):
    """Return (status, paths[], route) from the leading frontmatter block, tolerant of extra keys."""
    m = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None, [], None
    status = None
    route = None
    paths = []
    in_paths = False
    for line in m.group(1).splitlines():
        if re.match(r"^status:\s*(.+)$", line):
            status = line.split(":", 1)[1].strip()
            in_paths = False
        elif re.match(r"^route:\s*(.+)$", line):
            route = line.split(":", 1)[1].strip()
            in_paths = False
        elif re.match(r"^paths:\s*$", line):
            in_paths = True
        elif in_paths:
            pm = re.match(r'^\s+-\s+"?([^"]+?)"?\s*$', line)
            if pm:
                paths.append(pm.group(1))
            else:
                in_paths = False
        elif re.match(r"^\S", line):
            in_paths = False
    return status, paths, route


def main() -> int:
    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    reg_rel = registry_dir_rel()
    patterns_dir = os.path.join(root, reg_rel)
    out_path = os.path.join(patterns_dir, TSV_NAME)

    if not os.path.isdir(patterns_dir):
        print(f"no registry dir at {patterns_dir} (set PATTERN_REGISTRY_DIR); nothing to do")
        return 0

    rows = []
    for name in sorted(os.listdir(patterns_dir)):
        if not name.endswith(".md") or name == "README.md":
            continue
        with open(os.path.join(patterns_dir, name), encoding="utf-8") as f:
            status, paths, route = parse_frontmatter(f.read())
        if status is None or not paths:
            continue
        route = route if route in ("edit", "land") else "edit"
        for glob in paths:
            rows.append((glob, f"{reg_rel}/{name}".replace(os.sep, "/"), status, route))

    header = (
        f"# GENERATED by the patterns plugin's generate-pattern-routes.py — do not edit by hand.\n"
        f"# Regenerate after any `paths:`/`route:`/`status:` frontmatter change; commit alongside it.\n"
        f"# Columns: glob \\t pattern-file \\t status \\t route(edit|land)\n"
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)
        for glob, pattern, status, route in rows:
            f.write(f"{glob}\t{pattern}\t{status}\t{route}\n")

    edit_n = sum(1 for r in rows if r[3] == "edit")
    print(f"{out_path}: {len(rows)} rows ({edit_n} edit-routed) from {patterns_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
